global:
  scrape_interval: 15s  # Default scrape interval (15 seconds)
  evaluation_interval: 15s  # How frequently to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']  # Node Exporter running on the same host
